name: Financial Data Automation

on:
  schedule:
    - cron: '0 0 * * *' # every day at 00:00
  workflow_dispatch:      # trigger manually

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Libraries
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas vaderSentiment sqlalchemy psycopg2-binary

    - name: Execute Data Pipeline
      run: python main.py

    - name: Save CSV Results
      uses: actions/upload-artifact@v4
      with:
        name: stock-sentiment-results # folder name
        path: |
          files/stock_prices.csv
          files/stock_news.csv

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Auto-update financial data [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi